config/routes.rb
Rails.application.routes.draw do
  root "projects#index"
  resources :projects do 
    resources :tickets
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :tickets, dependent: :delete_all
    validates :name, presence: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :project
  validates :name, presence: true
  validates :description, presence: true
  validates :description, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :set_project, only: [:show, :edit, :update, :destroy] 
    def show 
    end
    def index
        @projects = Project.all
    end
    def edit
    end
    def new
        @project = Project.new
    end
    def destroy
        @project.destroy
        flash[:notice] = "Project has been deleted." 
        redirect_to projects_path
    end
    def update
        if @project.update(project_params)
            flash[:notice] = "Project has been updated."
            redirect_to @project
        else
            flash.now[:alert] = "Project has not been updated."
            render "edit"
        end
    end
    def create
        @project = Project.new(project_params)

        if @project.save
            flash[:notice] = "Project has been created."
            redirect_to @project
        else
            flash.now[:alert] = "Project has not been created."
            render "new"
        end
    end

    private
    
    def project_params
        params.require(:project).permit(:name, :description)
    end
    def set_project
        @project = Project.find(params[:id]) 
        rescue ActiveRecord::RecordNotFound
        flash[:alert] = "The project you were looking for could not be found." 
        redirect_to projects_path 
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
    before_action :set_project
    before_action :set_ticket, only: [:edit, :update, :show, :destroy]

    def show
    end
    def new
        @ticket = @project.tickets.new
    end
    def update
        if @ticket.update(ticket_params)
            flash[:notice] = "Ticket has been updated."
            redirect_to [@project, @ticket]
        else
            flash.now[:alert] = "Ticket has not been updated."
            render "edit"
        end
    end
    def create
        @ticket = @project.tickets.build(ticket_params)
        if @ticket.save
            flash[:notice] = "Ticket has been created."
            redirect_to [@project, @ticket]
        else
            flash.now[:alert] = "Ticket has not been created."
            render "new"
        end
    end
    def destroy
        @ticket.destroy
        flash[:notice] = "Ticket has been deleted." 
        redirect_to @project
    end


private

    def set_project
        @project = Project.find(params[:project_id])
    end
    def set_ticket
        @ticket = @project.tickets.find(params[:id])
    end
    def ticket_params
        params.require(:ticket).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
    def title(*parts) 
        unless parts.empty? 
            content_for :title do 
                (parts << "Oyga").join(" - ") 
            end 
        end 
    end 
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      <% if content_for?(:title)%>
        <%= yield(:title)%>
      <%else%>
        Oyga
      <%end%>  
    </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Ticketee", root_path, class: "navbar-brand" %>
          <button type="button" class="navbar-toggle collapsed"data-toggle="collapse" data-target="#collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="collapse">
          <ul class="nav navbar-nav">
            <li class="<%= "active" if current_page?("/") %>">
            <%= link_to "Home", root_path %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |key, message| %>
        <div class="alert alert-<%= key %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for(project) do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.button :submit, class: 'btn-primary' %>
<% end %>

app/views/projects/edit.html.erb
<header>
    <h1>Edit Project</h1> 
</header>
<%= render "form", project: @project %>

app/views/projects/index.html.erb
<header>
    <h1>Projects</h1>
    <ul class="actions">
        <%= link_to "New Project", new_project_path, class: "new" %>
    </ul>
</header>

<div id="projects">
    <%@projects.each do |project| %>
        <h2><%= link_to project.name, project %></h2>
        <p><%= project.description %></p>
    <%end%>
</div>

app/views/projects/new.html.erb
<header>
    <h1>New Project</h1>
</header>
<%= render "form", project: @project %>

app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>
<header>
    <h1><%= @project.name %></h1>
    <ul class="actions">
        <li><%= link_to "Edit Project", edit_project_path(@project),
            class: "edit" %></li>
        <li><%= link_to "Delete Project", project_path(@project),
            method: :delete,
            data: { confirm: "Are you sure you want to delete this project?" },
            class: "delete" %></li>
    </ul>
</header>
<p><%= @project.description %></p>
<header>
    <h2>Tickets</h2>
    <ul class="actions">
        <li><%= link_to "New Ticket", new_project_ticket_path(@project), class: "new" %></li>
    </ul>
</header>
<ul id="tickets">
    <% @project.tickets.each do |ticket| %>
    <li>
        #<%= ticket.id %> -
        <%= link_to ticket.name, [@project, ticket] %>
    </li>
    <% end %>
</ul>

app/views/tickets/_form.html.erb
<%= simple_form_for([project, ticket]) do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/tickets/edit.html.erb
<header>
    <h1>Edit Project</h1> 
</header>
<%= render "form", project: @project, ticket: @ticket %>

app/views/tickets/new.html.erb
<header>
    <h1>
        New Ticket
        <small><%= @project.name %></small>
    </h1>
</header>

<%= render "form", project: @project, ticket: @ticket %>

app/views/tickets/show.html.erb
<% title(@ticket.name, "Tickets") %>
<header>
    <h1><%= @ticket.name %></h1>
    <ul class="actions">
        <li><%= link_to "Edit Ticket", edit_project_ticket_path(@ticket),
            class: "edit" %></li>
        <li><%= link_to "Delete Ticket", project_ticket_path(@project, @ticket),
            method: :delete,
            data: { confirm: "Are you sure you want to delete this ticket?" },
            class: "delete" %></li>
    </ul>
</header>
<p><%= @ticket.description %></p>